In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [5]:
excel_file = pd.ExcelFile('../datasetventoinha/falha total_features_ventilador.xlsx')
print("Abas encontradas:", excel_file.sheet_names)

df_window_falhatotal = pd.read_excel('../datasetventoinha/falha total_features_ventilador.xlsx', sheet_name='Features_por_Janela')
df_window_falhatotal.info()

df_window_falhatotal.head()

Abas encontradas: ['Features_por_Janela', 'Features_Globais']
<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Tempo_centro_seg       60 non-null     float64
 1   Ax_Mean                60 non-null     float64
 2   Ax_Variance            60 non-null     float64
 3   Ax_RMS                 60 non-null     float64
 4   Ax_Skewness            60 non-null     float64
 5   Ax_Kurtosis            60 non-null     float64
 6   Ax_Peak_to_Peak        60 non-null     float64
 7   Ax_Max_Amp             60 non-null     float64
 8   Ax_Crest_Factor        60 non-null     float64
 9   Ay_Mean                60 non-null     float64
 10  Ay_Variance            60 non-null     float64
 11  Ay_RMS                 60 non-null     float64
 12  Ay_Skewness            60 non-null     float64
 13  Ay_Kurtosis            60 non-null     float64
 14  Ay_Peak_to_Peak        60 non-null     float64
 15  Ay_Max_Amp             60 non-null     float64
 16  Ay_Crest_Factor        60 non-null     float64
 17  Az_Mean                60 non-null     float64
 18  Az_Variance            60 non-null     float64
 19  Az_RMS                 60 non-null     float64
 20  Az_Skewness            60 non-null     float64
 21  Az_Kurtosis            60 non-null     float64
 22  Az_Peak_to_Peak        60 non-null     float64
 23  Az_Max_Amp             60 non-null     float64
 24  Az_Crest_Factor        60 non-null     float64
 25  Vibracao_Mean          60 non-null     float64
 26  Vibracao_Variance      60 non-null     float64
 27  Vibracao_RMS           60 non-null     float64
 28  Vibracao_Skewness      60 non-null     float64
 29  Vibracao_Kurtosis      60 non-null     float64
 30  Vibracao_Peak_to_Peak  60 non-null     float64
 31  Vibracao_Max_Amp       60 non-null     float64
 32  Vibracao_Crest_Factor  60 non-null     float64
dtypes: float64(33)
memory usage: 15.6 KB

,Tempo_centro_seg,Ax_Mean,Ax_Variance,Ax_RMS,Ax_Skewness,Ax_Kurtosis,Ax_Peak_to_Peak,Ax_Max_Amp,Ax_Crest_Factor,Ay_Mean,...,Az_Max_Amp,Az_Crest_Factor,Vibracao_Mean,Vibracao_Variance,Vibracao_RMS,Vibracao_Skewness,Vibracao_Kurtosis,Vibracao_Peak_to_Peak,Vibracao_Max_Amp,Vibracao_Crest_Factor
0,0.497777,0.038995,0.012048,0.116329,0.023184,1.655314,0.374428,0.215212,1.850025,-0.023680,...,1.154409,1.101292,0.067693,0.000968,0.074484,0.160205,2.260996,0.152203,0.155420,2.086630
1,1.496295,0.040978,0.011220,0.113427,-0.017541,1.668366,0.362490,0.207110,1.825937,-0.023766,...,1.157467,1.104248,0.066644,0.000914,0.073161,0.188873,2.402209,0.155523,0.158449,2.165755
2,2.494813,0.039824,0.011234,0.113079,0.000870,1.691507,0.375404,0.213630,1.889212,-0.024313,...,1.140682,1.088092,0.067527,0.000858,0.073592,0.123726,2.480194,0.143255,0.146212,1.986792
3,3.493331,0.042343,0.011551,0.115369,-0.028405,1.629968,0.378394,0.216275,1.874635,-0.023471,...,1.138193,1.086396,0.066645,0.000856,0.072767,0.024683,2.461900,0.138384,0.141227,1.940802
4,4.491849,0.040466,0.011184,0.113085,0.022330,1.669519,0.375719,0.209825,1.855462,-0.024522,...,1.141909,1.088595,0.067756,0.000928,0.074268,0.107834,2.298090,0.141258,0.146688,1.975126

In [6]:
excel_file = pd.ExcelFile('../datasetventoinha/falha total_features_ventilador.xlsx')
print("Abas encontradas:", excel_file.sheet_names)

df_window_falhaparcial = pd.read_excel('../datasetventoinha/umquarto_parcialfeatures_ventilador.xlsx', sheet_name='Features_por_Janela')
df_window_falhaparcial.info()

df_window_falhaparcial.head()

Abas encontradas: ['Features_por_Janela', 'Features_Globais']
<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Tempo_centro_seg       60 non-null     float64
 1   Ax_Mean                60 non-null     float64
 2   Ax_Variance            60 non-null     float64
 3   Ax_RMS                 60 non-null     float64
 4   Ax_Skewness            60 non-null     float64
 5   Ax_Kurtosis            60 non-null     float64
 6   Ax_Peak_to_Peak        60 non-null     float64
 7   Ax_Max_Amp             60 non-null     float64
 8   Ax_Crest_Factor        60 non-null     float64
 9   Ay_Mean                60 non-null     float64
 10  Ay_Variance            60 non-null     float64
 11  Ay_RMS                 60 non-null     float64
 12  Ay_Skewness            60 non-null     float64
 13  Ay_Kurtosis            60 non-null     float64
 14  Ay_Peak_to_Peak        60 non-null     float64
 15  Ay_Max_Amp             60 non-null     float64
 16  Ay_Crest_Factor        60 non-null     float64
 17  Az_Mean                60 non-null     float64
 18  Az_Variance            60 non-null     float64
 19  Az_RMS                 60 non-null     float64
 20  Az_Skewness            60 non-null     float64
 21  Az_Kurtosis            60 non-null     float64
 22  Az_Peak_to_Peak        60 non-null     float64
 23  Az_Max_Amp             60 non-null     float64
 24  Az_Crest_Factor        60 non-null     float64
 25  Vibracao_Mean          60 non-null     float64
 26  Vibracao_Variance      60 non-null     float64
 27  Vibracao_RMS           60 non-null     float64
 28  Vibracao_Skewness      60 non-null     float64
 29  Vibracao_Kurtosis      60 non-null     float64
 30  Vibracao_Peak_to_Peak  60 non-null     float64
 31  Vibracao_Max_Amp       60 non-null     float64
 32  Vibracao_Crest_Factor  60 non-null     float64
dtypes: float64(33)
memory usage: 15.6 KB

,Tempo_centro_seg,Ax_Mean,Ax_Variance,Ax_RMS,Ax_Skewness,Ax_Kurtosis,Ax_Peak_to_Peak,Ax_Max_Amp,Ax_Crest_Factor,Ay_Mean,...,Az_Max_Amp,Az_Crest_Factor,Vibracao_Mean,Vibracao_Variance,Vibracao_RMS,Vibracao_Skewness,Vibracao_Kurtosis,Vibracao_Peak_to_Peak,Vibracao_Max_Amp,Vibracao_Crest_Factor
0,0.497188,0.035982,0.007706,0.094750,0.348615,1.854105,0.304444,0.213154,2.249638,-0.000462,...,1.151264,1.102883,0.062222,0.001184,0.071075,0.698186,2.844820,0.153291,0.154084,2.167909
1,1.494524,0.031025,0.007825,0.093617,0.389160,1.901846,0.316292,0.221413,2.365091,-0.000246,...,1.165470,1.115735,0.064454,0.001307,0.073871,0.804975,3.093885,0.165018,0.169168,2.290034
2,2.491860,0.029270,0.007653,0.092127,0.382862,1.928122,0.325905,0.217203,2.357654,0.001385,...,1.159972,1.111336,0.063069,0.001239,0.072204,0.794396,3.091538,0.161541,0.162934,2.256574
3,3.489196,0.029175,0.007788,0.092825,0.423722,1.902023,0.318915,0.213844,2.303748,0.001745,...,1.179459,1.129025,0.063569,0.001243,0.072666,0.902321,3.618726,0.180733,0.183617,2.526867
4,4.486531,0.028944,0.008055,0.094176,0.395843,1.843913,0.320781,0.214495,2.277611,0.000948,...,1.169870,1.120650,0.061853,0.001329,0.071770,0.826315,3.144950,0.170976,0.173281,2.414406

In [7]:
excel_file = pd.ExcelFile('../datasetventoinha/falha total_features_ventilador.xlsx')
print("Abas encontradas:", excel_file.sheet_names)

df_window_semfalha = pd.read_excel('../datasetventoinha/falha total_features_ventilador.xlsx', sheet_name='Features_por_Janela')
df_window_semfalha.info()

df_window_semfalha.head()

Abas encontradas: ['Features_por_Janela', 'Features_Globais']
<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Tempo_centro_seg       60 non-null     float64
 1   Ax_Mean                60 non-null     float64
 2   Ax_Variance            60 non-null     float64
 3   Ax_RMS                 60 non-null     float64
 4   Ax_Skewness            60 non-null     float64
 5   Ax_Kurtosis            60 non-null     float64
 6   Ax_Peak_to_Peak        60 non-null     float64
 7   Ax_Max_Amp             60 non-null     float64
 8   Ax_Crest_Factor        60 non-null     float64
 9   Ay_Mean                60 non-null     float64
 10  Ay_Variance            60 non-null     float64
 11  Ay_RMS                 60 non-null     float64
 12  Ay_Skewness            60 non-null     float64
 13  Ay_Kurtosis            60 non-null     float64
 14  Ay_Peak_to_Peak        60 non-null     float64
 15  Ay_Max_Amp             60 non-null     float64
 16  Ay_Crest_Factor        60 non-null     float64
 17  Az_Mean                60 non-null     float64
 18  Az_Variance            60 non-null     float64
 19  Az_RMS                 60 non-null     float64
 20  Az_Skewness            60 non-null     float64
 21  Az_Kurtosis            60 non-null     float64
 22  Az_Peak_to_Peak        60 non-null     float64
 23  Az_Max_Amp             60 non-null     float64
 24  Az_Crest_Factor        60 non-null     float64
 25  Vibracao_Mean          60 non-null     float64
 26  Vibracao_Variance      60 non-null     float64
 27  Vibracao_RMS           60 non-null     float64
 28  Vibracao_Skewness      60 non-null     float64
 29  Vibracao_Kurtosis      60 non-null     float64
 30  Vibracao_Peak_to_Peak  60 non-null     float64
 31  Vibracao_Max_Amp       60 non-null     float64
 32  Vibracao_Crest_Factor  60 non-null     float64
dtypes: float64(33)
memory usage: 15.6 KB

,Tempo_centro_seg,Ax_Mean,Ax_Variance,Ax_RMS,Ax_Skewness,Ax_Kurtosis,Ax_Peak_to_Peak,Ax_Max_Amp,Ax_Crest_Factor,Ay_Mean,...,Az_Max_Amp,Az_Crest_Factor,Vibracao_Mean,Vibracao_Variance,Vibracao_RMS,Vibracao_Skewness,Vibracao_Kurtosis,Vibracao_Peak_to_Peak,Vibracao_Max_Amp,Vibracao_Crest_Factor
0,0.497777,0.038995,0.012048,0.116329,0.023184,1.655314,0.374428,0.215212,1.850025,-0.023680,...,1.154409,1.101292,0.067693,0.000968,0.074484,0.160205,2.260996,0.152203,0.155420,2.086630
1,1.496295,0.040978,0.011220,0.113427,-0.017541,1.668366,0.362490,0.207110,1.825937,-0.023766,...,1.157467,1.104248,0.066644,0.000914,0.073161,0.188873,2.402209,0.155523,0.158449,2.165755
2,2.494813,0.039824,0.011234,0.113079,0.000870,1.691507,0.375404,0.213630,1.889212,-0.024313,...,1.140682,1.088092,0.067527,0.000858,0.073592,0.123726,2.480194,0.143255,0.146212,1.986792
3,3.493331,0.042343,0.011551,0.115369,-0.028405,1.629968,0.378394,0.216275,1.874635,-0.023471,...,1.138193,1.086396,0.066645,0.000856,0.072767,0.024683,2.461900,0.138384,0.141227,1.940802
4,4.491849,0.040466,0.011184,0.113085,0.022330,1.669519,0.375719,0.209825,1.855462,-0.024522,...,1.141909,1.088595,0.067756,0.000928,0.074268,0.107834,2.298090,0.141258,0.146688,1.975126

In [ ]:
# Agora o 'plt' e o 'sns' estarão definidos
plt.switch_backend('QtAgg')

# Configuração de tema
sns.set_theme(style="whitegrid", font="DejaVu Sans")
# Ativa o backend iterativo para janelas pop-up
plt.switch_backend('TkAgg')

# Configuração global de tema e estética (UI)
sns.set_theme(style="whitegrid", font="DejaVu Sans")
plt.rcParams.update({
    'figure.facecolor': '#FAFAFA',
    'axes.facecolor': '#FFFFFF',
    'axes.edgecolor': '#E0E0E0',
    'axes.titleweight': 'bold',
    'axes.titlepad': 12,
    'font.size': 10
})

# 1. Carga do Dataset e Treinamento do Modelo
data = load_breast_cancer()
X = pd.DataFrame(data.data, columns=data.feature_names)
y = data.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train_scaled, y_train)

y_pred = rf.predict(X_test_scaled)
acc = accuracy_score(y_test, y_pred)

# ==========================================================
# POP-UP 1: Dashboard de Avaliação do Modelo
# ==========================================================
fig1, (ax_cm, ax_kpi) = plt.subplots(1, 2, figsize=(11, 5), gridspec_kw={'width_ratios': [2, 1]})
fig1.canvas.manager.set_window_title('ML Dashboard - Performance do Modelo')

# Matriz de Confusão
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='mako', cbar=False, ax=ax_cm,
            xticklabels=data.target_names, yticklabels=data.target_names,
            annot_kws={"size": 16, "weight": "bold", "color": "white"})

ax_cm.set_title("Matriz de Confusão", fontsize=13)
ax_cm.set_xlabel("Rótulo Predito", labelpad=8)
ax_cm.set_ylabel("Rótulo Real", labelpad=8)

# Card de Acurácia (KPI)
ax_kpi.axis('off')
ax_kpi.text(0.5, 0.65, f"{acc * 100:.1f}%", fontsize=38, fontweight='bold',
            color='#1b4332', ha='center', va='center')
ax_kpi.text(0.5, 0.45, "Acurácia Geral", fontsize=13, color='#555555',
            ha='center', va='center')
ax_kpi.add_patch(plt.Rectangle((0.05, 0.25), 0.9, 0.5, fill=False,
                               edgecolor='#2d6a4f', lw=2, linestyle='--'))

plt.tight_layout(pad=2.0)

# ==========================================================
# POP-UP 2: Análise de Importância das Features
# ==========================================================
fig2, ax_feat = plt.subplots(figsize=(10, 5.5))
fig2.canvas.manager.set_window_title('ML Dashboard - Importância das Características')

# Top 10 atributos
importances = pd.Series(rf.feature_importances_, index=data.feature_names).nlargest(10).sort_values()

# Gráfico de barras com remoção limpa de legenda
sns.barplot(x=importances.values, y=importances.index, hue=importances.index,
            palette='crest', ax=ax_feat)

if ax_feat.legend_:
    ax_feat.legend_.remove()

ax_feat.set_title("Top 10 Features Relevantes (Random Forest)", fontsize=13)
ax_feat.set_xlabel("Grau de Importância (Gini Impurity)", labelpad=8)
ax_feat.spines['top'].set_visible(False)
ax_feat.spines['right'].set_visible(False)

# Adiciona os rótulos numéricos
for i, v in enumerate(importances.values):
    ax_feat.text(v + 0.002, i, f"{v:.3f}", va='center', fontsize=9, color='#333333')

plt.tight_layout(pad=2.0)

# Exibe as janelas simultaneamente
plt.show()

ModuleNotFoundError: No module named 'tkinter'